[2025-02-08T05:53:33.506+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T05:53:33.781+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Incident_Report_Generation.procesar_logs_up_down manual__2025-02-08T05:47:23.392070+00:00 [queued]>
[2025-02-08T05:53:33.815+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Incident_Report_Generation.procesar_logs_up_down manual__2025-02-08T05:47:23.392070+00:00 [queued]>
[2025-02-08T05:53:33.823+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-08T05:53:34.273+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): procesar_logs_up_down> on 2025-02-08 05:47:23.392070+00:00
[2025-02-08T05:53:34.419+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Incident_Report_Generation', 'procesar_logs_up_down', 'manual__2025-02-08T05:47:23.392070+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/Incident_Report_Generation.py', '--cfg-path', '/tmp/tmpyigg1srm']
[2025-02-08T05:53:34.457+0000] {standard_task_runner.py:105} INFO - Job 156: Subtask procesar_logs_up_down
[2025-02-08T05:53:34.377+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3489) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-08T05:53:34.470+0000] {standard_task_runner.py:72} INFO - Started process 3498 to run task
[2025-02-08T05:53:34.700+0000] {task_command.py:467} INFO - Running <TaskInstance: Incident_Report_Generation.procesar_logs_up_down manual__2025-02-08T05:47:23.392070+00:00 [running]> on host 0b0ecc2e9e80
[2025-02-08T05:53:35.117+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Incident_Report_Generation' AIRFLOW_CTX_TASK_ID='procesar_logs_up_down' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T05:47:23.392070+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-08T05:47:23.392070+00:00'
[2025-02-08T05:53:35.118+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-08T05:53:35.123+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-08T05:53:35.131+0000] {logging_mixin.py:190} INFO - Current task name:procesar_logs_up_down state:running start_date:2025-02-08 05:53:33.782601+00:00
[2025-02-08T05:53:35.143+0000] {logging_mixin.py:190} INFO - Dag name:Incident_Report_Generation and current dag run status:running
[2025-02-08T05:53:35.167+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T05:53:35.526+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Incident_Report_Generation.py", line 145, in procesar_logs_up_down
    interface_changes = [(log["device"], "0.0.0.0", log["timestamp"], log["message"]) for log in logs if "up" in log["message"] or "down" in log["message"]]
                                                                                                                 ~~~^^^^^^^^^^^
TypeError: tuple indices must be integers or slices, not str
[2025-02-08T05:53:35.667+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-08T05:53:35.669+0000] {logging_mixin.py:190} INFO - Task start:2025-02-08 05:53:33.782601+00:00 end:2025-02-08 05:53:35.666519+00:00 duration:1.883918
[2025-02-08T05:53:35.670+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): procesar_logs_up_down> dag:<DAG: Incident_Report_Generation> dagrun:<DagRun Incident_Report_Generation @ 2025-02-08 05:47:23.392070+00:00: manual__2025-02-08T05:47:23.392070+00:00, state:running, queued_at: 2025-02-08 05:47:24.004302+00:00. externally triggered: True>
[2025-02-08T05:53:35.672+0000] {logging_mixin.py:190} INFO - Failure caused by tuple indices must be integers or slices, not str
[2025-02-08T05:53:35.674+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Incident_Report_Generation, task_id=procesar_logs_up_down, run_id=manual__2025-02-08T05:47:23.392070+00:00, execution_date=20250208T054723, start_date=20250208T055333, end_date=20250208T055335
[2025-02-08T05:53:35.714+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T05:53:35.715+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 156 for task procesar_logs_up_down (tuple indices must be integers or slices, not str; 3498)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Incident_Report_Generation.py", line 145, in procesar_logs_up_down
    interface_changes = [(log["device"], "0.0.0.0", log["timestamp"], log["message"]) for log in logs if "up" in log["message"] or "down" in log["message"]]
                                                                                                                 ~~~^^^^^^^^^^^
TypeError: tuple indices must be integers or slices, not str
[2025-02-08T05:53:35.814+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-08T05:53:35.885+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
