[2025-02-08T08:17:28.659+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T08:17:28.961+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Incident_Report_Generation.generar_reporte manual__2025-02-08T08:09:36.584064+00:00 [queued]>
[2025-02-08T08:17:29.017+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Incident_Report_Generation.generar_reporte manual__2025-02-08T08:09:36.584064+00:00 [queued]>
[2025-02-08T08:17:29.034+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-08T08:17:29.099+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generar_reporte> on 2025-02-08 08:09:36.584064+00:00
[2025-02-08T08:17:29.129+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5540) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-08T08:17:29.132+0000] {standard_task_runner.py:72} INFO - Started process 5551 to run task
[2025-02-08T08:17:29.213+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Incident_Report_Generation', 'generar_reporte', 'manual__2025-02-08T08:09:36.584064+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/Incident_Report_Generation.py', '--cfg-path', '/tmp/tmpewcceo2x']
[2025-02-08T08:17:29.216+0000] {standard_task_runner.py:105} INFO - Job 267: Subtask generar_reporte
[2025-02-08T08:17:30.133+0000] {task_command.py:467} INFO - Running <TaskInstance: Incident_Report_Generation.generar_reporte manual__2025-02-08T08:09:36.584064+00:00 [running]> on host 0b0ecc2e9e80
[2025-02-08T08:17:30.831+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Incident_Report_Generation' AIRFLOW_CTX_TASK_ID='generar_reporte' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T08:09:36.584064+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-08T08:09:36.584064+00:00'
[2025-02-08T08:17:30.879+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-08T08:17:30.880+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-08T08:17:30.881+0000] {logging_mixin.py:190} INFO - Current task name:generar_reporte state:running start_date:2025-02-08 08:17:28.962478+00:00
[2025-02-08T08:17:30.882+0000] {logging_mixin.py:190} INFO - Dag name:Incident_Report_Generation and current dag run status:running
[2025-02-08T08:17:30.884+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T08:17:32.051+0000] {logging_mixin.py:190} INFO - {'restart_logs': [[351, datetime.datetime(2025, 2, 8, 0, 48, 32), 'RESTART sw9Portoviejo'], [1765, datetime.datetime(2025, 2, 8, 1, 48), 'RESTART sw40Babahoyo'], [1868, datetime.datetime(2025, 2, 8, 1, 52, 22), 'RESTART sw56Chone'], [2713, datetime.datetime(2025, 2, 8, 2, 28, 18), 'RESTART sw9Portoviejo']], 'total_equipos_reiniciados': 3, 'top_equipos': ['sw9Portoviejo', 2]}
[2025-02-08T08:17:32.057+0000] {logging_mixin.py:190} INFO - {'reporte': 'Reporte de caídas de equipos (unavailably by ICMP)\n\nEquipo | IP | Timestamp de caída | Número de caídas\n--------------------------------------------------------------------------------\nro19Salinas | 10.19.1.1 | 2025-02-08 00:55:12 | 1\nsw57Duran | 10.17.57.1 | 2025-02-08 01:03:07 | 1\nsw80Babahoyo | 10.20.80.1 | 2025-02-08 01:21:29 | 1\nsw56Chone | 10.16.56.1 | 2025-02-08 01:31:05 | 1\nro3Cuenca | 10.3.1.1 | 2025-02-08 01:31:27 | 1\nsw28Loja | 10.8.28.1 | 2025-02-08 01:40:12 | 1\nsw59Salinas | 10.19.59.1 | 2025-02-08 02:01:41 | 1\nsw48Loja | 10.8.48.1 | 2025-02-08 02:07:16 | 1\nsw6Manta | 10.6.6.1 | 2025-02-08 02:13:59 | 1\nsw9Portoviejo | 10.9.9.1 | 2025-02-08 02:22:17 | 1\nsw38Loja | 10.18.38.1 | 2025-02-08 02:30:14 | 1\n\nEquipo con más caídas: ro19Salinas con 1 caídas.\n', 'total_equipos_caidos': 11, 'equipo_mas_caidas': ['ro19Salinas', {'ip': '10.19.1.1', 'caidas': 1, 'fechas': [datetime.datetime(2025, 2, 8, 0, 55, 12)]}]}
[2025-02-08T08:17:32.065+0000] {logging_mixin.py:190} INFO - {'reporte_down': 'Reporte de caídas de interfaces (down)\n\nTimestamp de caída | Mensaje\n--------------------------------------------------------------------------------\n2025-02-08 00:34:29 | Interface is down sw63Cuenca TenGigaEthernet1/2\n2025-02-08 00:34:58 | Interface is down sw30Esmeraldas GigaEthernet1/8\n2025-02-08 00:40:37 | Interface is down sw55Latacunga TenGigaEthernet1/2\n2025-02-08 00:48:02 | Interface is down sw21Quito GigaEthernet1/4\n2025-02-08 00:50:44 | Interface is down sw53Tulcan GigaEthernet1/4\n2025-02-08 00:50:56 | Interface is down sw62Guayaquil GigaEthernet1/6\n2025-02-08 00:53:50 | Interface is down sw66Manta GigaEthernet1/4\n2025-02-08 00:54:14 | Interface is down sw23Cuenca GigaEthernet1/2\n2025-02-08 00:55:26 | Interface is down sw71Riobamba GigaEthernet1/8\n2025-02-08 00:59:20 | Interface is down sw57Duran GigaEthernet1/3\n2025-02-08 01:00:03 | Interface is down sw13Tulcan GigaEthernet1/5\n2025-02-08 01:01:55 | Interface is down sw43Cuenca GigaEthernet1/3\n2025-02-08 01:04:14 | Interface is down ro4SantoDomingo TenGigaEthernet2/3\n2025-02-08 01:06:30 | Interface is down ro9Portoviejo TenGigaEthernet1/1\n2025-02-08 01:08:13 | Interface is down ro3Cuenca GigaEthernet1/1\n2025-02-08 01:08:48 | Interface is down sw16Chone GigaEthernet1/6\n2025-02-08 01:12:30 | Interface is down ro15Latacunga TenGigaEthernet2/3\n2025-02-08 01:13:20 | Interface is down sw76Chone GigaEthernet1/4\n2025-02-08 01:19:17 | Interface is down sw28Loja GigaEthernet1/7\n2025-02-08 01:19:52 | Interface is down sw14Quevedo GigaEthernet1/6\n2025-02-08 01:19:59 | Interface is down sw23Cuenca GigaEthernet1/5\n2025-02-08 01:22:35 | Interface is down sw27Ambato GigaEthernet1/7\n2025-02-08 01:25:00 | Interface is down sw57Duran GigaEthernet1/7\n2025-02-08 01:25:12 | Interface is down ro7Ambato TenGigaEthernet2/3\n2025-02-08 01:26:03 | Interface is down sw79Salinas GigaEthernet1/5\n2025-02-08 01:27:34 | Interface is down sw24SantoDomingo GigaEthernet1/8\n2025-02-08 01:29:33 | Interface is down sw67Ambato GigaEthernet1/4\n2025-02-08 01:30:08 | Interface is down sw28Loja TenGigaEthernet1/1\n2025-02-08 01:34:13 | Interface is down sw7Ambato GigaEthernet1/3\n2025-02-08 01:37:33 | Interface is down sw22Guayaquil TenGigaEthernet1/2\n2025-02-08 01:38:38 | Interface is down ro19Salinas TenGigaEthernet1/1\n2025-02-08 01:41:24 | Interface is down sw39Salinas GigaEthernet1/2\n2025-02-08 01:44:04 | Interface is down ro5Machala GigaEthernet1/2\n2025-02-08 01:47:41 | Interface is down sw6Manta GigaEthernet1/5\n2025-02-08 01:48:05 | Interface is down sw41Quito GigaEthernet1/5\n2025-02-08 01:53:22 | Interface is down sw31Riobamba TenGigaEthernet1/2\n2025-02-08 01:53:31 | Interface is down sw10Esmeraldas GigaEthernet1/4\n2025-02-08 01:59:00 | Interface is down sw60Babahoyo GigaEthernet1/2\n2025-02-08 02:04:54 | Interface is down sw36Chone GigaEthernet1/6\n2025-02-08 02:08:26 | Interface is down sw50Esmeraldas GigaEthernet1/5\n2025-02-08 02:10:03 | Interface is down sw2Guayaquil GigaEthernet1/7\n2025-02-08 02:15:42 | Interface is down sw57Duran GigaEthernet1/5\n2025-02-08 02:18:59 | Interface is down sw67Ambato GigaEthernet1/7\n2025-02-08 02:19:01 | Interface is down ro12Ibarra TenGigaEthernet1/1\n2025-02-08 02:20:05 | Interface is down sw73Tulcan GigaEthernet1/4\n2025-02-08 02:28:10 | Interface is down sw61Quito GigaEthernet1/6\n2025-02-08 02:35:08 | Interface is down sw51Riobamba GigaEthernet1/8\n2025-02-08 02:36:28 | Interface is down sw73Tulcan GigaEthernet1/7\n2025-02-08 02:39:18 | Interface is down sw46Manta GigaEthernet1/7\n2025-02-08 02:39:36 | Interface is down sw27Ambato GigaEthernet1/3\n2025-02-08 02:42:01 | Interface is down sw58Loja TenGigaEthernet1/1\n2025-02-08 02:44:16 | Interface is down sw58Loja GigaEthernet1/5\n', 'reporte_up': 'Reporte de activaciones de interfaces (up)\n\nTimestamp de activación | Mensaje\n--------------------------------------------------------------------------------\n2025-02-08 00:34:32 | Interface is up sw68Loja GigaEthernet1/2\n2025-02-08 00:34:43 | Interface is up ro15Latacunga TenGigaEthernet1/1\n2025-02-08 00:35:23 | Interface is up sw56Chone GigaEthernet1/8\n2025-02-08 00:37:32 | Interface is up ro15Latacunga TenGigaEthernet1/2\n2025-02-08 00:40:26 | Interface is up sw30Esmeraldas GigaEthernet1/8\n2025-02-08 00:41:30 | Interface is up sw63Cuenca TenGigaEthernet1/2\n2025-02-08 00:42:51 | Interface is up sw32Ibarra GigaEthernet1/5\n2025-02-08 00:44:15 | Interface is up sw45Machala TenGigaEthernet1/2\n2025-02-08 00:46:31 | Interface is up sw55Latacunga TenGigaEthernet1/2\n2025-02-08 00:56:21 | Interface is up sw74Quevedo GigaEthernet1/8\n2025-02-08 00:57:18 | Interface is up sw43Cuenca GigaEthernet1/8\n2025-02-08 00:58:53 | Interface is up sw51Riobamba GigaEthernet1/7\n2025-02-08 00:58:58 | Interface is up sw78Loja GigaEthernet1/6\n2025-02-08 00:59:30 | Interface is up sw66Manta GigaEthernet1/4\n2025-02-08 01:02:26 | Interface is up sw23Cuenca GigaEthernet1/2\n2025-02-08 01:05:58 | Interface is up sw41Quito GigaEthernet1/3\n2025-02-08 01:07:29 | Interface is up sw13Tulcan GigaEthernet1/5\n2025-02-08 01:10:56 | Interface is up sw19Salinas TenGigaEthernet1/1\n2025-02-08 01:11:56 | Interface is up ro12Ibarra TenGigaEthernet2/3\n2025-02-08 01:13:03 | Interface is up sw57Duran GigaEthernet1/3\n2025-02-08 01:14:21 | Interface is up ro3Cuenca GigaEthernet1/1\n2025-02-08 01:14:36 | Interface is up ro1Quito TenGigaEthernet1/2\n2025-02-08 01:15:12 | Interface is up ro9Portoviejo TenGigaEthernet1/1\n2025-02-08 01:15:14 | Interface is up sw16Chone GigaEthernet1/6\n2025-02-08 01:15:51 | Interface is up sw51Riobamba TenGigaEthernet1/1\n2025-02-08 01:18:50 | Interface is up sw76Chone GigaEthernet1/4\n2025-02-08 01:19:50 | Interface is up sw54Quevedo GigaEthernet1/2\n2025-02-08 01:22:50 | Interface is up ro15Latacunga TenGigaEthernet2/3\n2025-02-08 01:23:34 | Interface is up ro15Latacunga TenGigaEthernet2/4\n2025-02-08 01:24:44 | Interface is up sw28Loja GigaEthernet1/7\n2025-02-08 01:26:20 | Interface is up sw14Quevedo GigaEthernet1/6\n2025-02-08 01:26:28 | Interface is up ro17Duran TenGigaEthernet1/2\n2025-02-08 01:32:50 | Interface is up ro7Ambato TenGigaEthernet2/3\n2025-02-08 01:39:53 | Interface is up sw28Loja TenGigaEthernet1/1\n2025-02-08 01:43:19 | Interface is up sw44SantoDomingo GigaEthernet1/7\n2025-02-08 01:44:19 | Interface is up ro19Salinas TenGigaEthernet1/1\n2025-02-08 01:47:29 | Interface is up sw22Guayaquil TenGigaEthernet1/2\n2025-02-08 01:47:53 | Interface is up ro11Riobamba GigaEthernet1/1\n2025-02-08 01:50:08 | Interface is up ro5Machala GigaEthernet1/2\n2025-02-08 01:53:05 | Interface is up sw6Manta GigaEthernet1/5\n2025-02-08 01:55:31 | Interface is up sw47Ambato GigaEthernet1/3\n2025-02-08 01:58:46 | Interface is up sw31Riobamba TenGigaEthernet1/2\n2025-02-08 01:59:36 | Interface is up sw4SantoDomingo GigaEthernet1/1\n2025-02-08 02:05:04 | Interface is up sw60Babahoyo GigaEthernet1/2\n2025-02-08 02:10:33 | Interface is up sw9Portoviejo GigaEthernet1/3\n2025-02-08 02:17:06 | Interface is up ro10Esmeraldas TenGigaEthernet1/2\n2025-02-08 02:21:41 | Interface is up sw57Duran GigaEthernet1/5\n2025-02-08 02:21:54 | Interface is up sw8Loja GigaEthernet1/4\n2025-02-08 02:24:34 | Interface is up sw10Esmeraldas TenGigaEthernet1/1\n2025-02-08 02:25:09 | Interface is up sw73Tulcan GigaEthernet1/4\n2025-02-08 02:27:14 | Interface is up ro11Riobamba TenGigaEthernet2/4\n2025-02-08 02:28:41 | Interface is up ro12Ibarra TenGigaEthernet1/1\n2025-02-08 02:29:23 | Interface is up sw63Cuenca GigaEthernet1/2\n2025-02-08 02:34:28 | Interface is up sw55Latacunga TenGigaEthernet1/1\n2025-02-08 02:35:58 | Interface is up sw71Riobamba GigaEthernet1/4\n2025-02-08 02:37:18 | Interface is up sw12Ibarra TenGigaEthernet1/1\n2025-02-08 02:38:35 | Interface is up sw1Quito GigaEthernet1/6\n2025-02-08 02:40:47 | Interface is up sw35Latacunga GigaEthernet1/4\n'}
[2025-02-08T08:17:32.228+0000] {base.py:84} INFO - Retrieving connection 'mysql_default1'
[2025-02-08T08:17:32.973+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Incident_Report_Generation.py", line 219, in generar_reporte
    restart_logs = restart_data["top_3_equipos"]
                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'top_3_equipos'
[2025-02-08T08:17:33.057+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-08T08:17:33.059+0000] {logging_mixin.py:190} INFO - Task start:2025-02-08 08:17:28.962478+00:00 end:2025-02-08 08:17:33.050599+00:00 duration:4.088121
[2025-02-08T08:17:33.062+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): generar_reporte> dag:<DAG: Incident_Report_Generation> dagrun:<DagRun Incident_Report_Generation @ 2025-02-08 08:09:36.584064+00:00: manual__2025-02-08T08:09:36.584064+00:00, state:running, queued_at: 2025-02-08 08:09:36.918396+00:00. externally triggered: True>
[2025-02-08T08:17:33.063+0000] {logging_mixin.py:190} INFO - Failure caused by 'top_3_equipos'
[2025-02-08T08:17:33.064+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Incident_Report_Generation, task_id=generar_reporte, run_id=manual__2025-02-08T08:09:36.584064+00:00, execution_date=20250208T080936, start_date=20250208T081728, end_date=20250208T081733
[2025-02-08T08:17:33.213+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T08:17:33.216+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 267 for task generar_reporte ('top_3_equipos'; 5551)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Incident_Report_Generation.py", line 219, in generar_reporte
    restart_logs = restart_data["top_3_equipos"]
                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'top_3_equipos'
[2025-02-08T08:17:33.269+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-08T08:17:33.333+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
